model:
  save_dir: saved_models/FactorVAE
  checkpoint: No checkpoint
  save_interval: 5
  z_dim: 10
  img_channels: 1
  gamma: 6.4
  init_mode: normal_init
  encoder:
    num_layers: 6
    channels: [32,32,64,64,128,20]
    kernel_sizes: [4,4,4,4,4,1]
    strides: [2,2,2,2,1,1]
    padding: [1,1,1,1,0,0]
    batch_norm: [True, True, True, True, True, False]
  decoder:
    num_layers: 6 
    channels: [128,64,64,32,32,1]
    kernel_sizes: [1,4,4,4,4,4]
    strides: [1,1,2,2,2,2]
    padding: [0,0,1,1,1,1]
    batch_norm: [True, True, True, True, True, False]
  discriminator:
    num_layers: 6
    hidden_dim: 1000
    out_dim: 2
    bn: [False, False, False, False, False, False]

data:
  name: dsprites
  root: data/Dsprites/dsprites_64.npz
  img_size: 28
  img_channels: 1
  batch_size: 32

train:
  num_epochs: 10
  lr_vae: 1.0e-4
  lr_discriminator: 1.0e-4
  optim: adam
  log_interval: 1
  log_result_dir: Reconstructions/FactorVAE

val:
  interval_step: 15

