encoder:
  in_channels: 1
  hidden_dim: 64

decoder:
  out_channels: 1
  hidden_dim: 64

vector_quantizer:
  num_embeddings: 10
  embedding_dim: 64
  commitment_cost: 1.0

siamese:
  coefficient: 0.25
  channels: 64
  dim: 64

train:
  num_epochs: 60
  optim: adam
  lr: 0.1e-4
  batch_size: 32
  log_interval: 1
  log_result_dir: Reconstructions

val:
  batch_size: 32
  interval_step: 10

model:
  save_dir: saved_models
  checkpoint: no_path
  save_interval: 5

data:
  name: mnist
  path: data/


  

